// <auto-generated />
namespace Siyouku.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class vicky7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vicky7));
        
        string IMigrationMetadata.Id
        {
            get { return "201612200558446_vicky7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
