// <auto-generated />
namespace Siyouku.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class vicky14 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(vicky14));
        
        string IMigrationMetadata.Id
        {
            get { return "201710120637473_vicky14"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
